### ISSUE TITLE
LUA assertion failed in premake5.lua

### ISSUE THREAD

**Issue by Caball009** [iw4x/iw4x-client#112]
**What problem will this solve?**
When trying to build the VS solution I'm getting two errors:
1. Error MSB3073 'The command "pushd ..' tools\premake5 generate-buildinfo
2. ... premake5.lua:117: assertion failed! https://github.com/iw4x/iw4x-client/blob/develop/premake5.lua#L117

**What might be a solution?**
This is merely a workaround, but I appear to have successfully sidestepped the issue by removing the lua assertion from line 117.

**Comment by diamante0018** [comment]
Read the build instructions, please (the first bullet point is the one that applies to you): https://github.com/iw4x/iw4x-client#readme

**Comment by Caball009** [comment]
I did clone the repo. I wouldn't expect the build to succeed at all if I hadn't but I haven't tested it.

**Comment by Rackover** [comment]
Git not installed on the system or not added to $PATH, i think!
Regardless not an issue with the premake scriptt
