### ISSUE TITLE
guid command does not work

### ISSUE THREAD

**Issue by diamante0018** [iw4x/iw4x-client#114]
**What are you trying to do?**
guid command in in-game console

**What problem are you having?**
Does not work
![image](https://github.com/iw4x/iw4x-client/assets/37080671/abc23bbb-e85e-4eae-abcc-5ddfb6c9fc54)

**What have you tried so far?**

**What version of IW4x are you using?**
r4508

**Anything else we should know?**

**Comment by mxve** [comment]
Didn't work for me either some time ago, but seems to be working again?
Both with Steam running and closed, so no interference on that part.
![image](https://github.com/user-attachments/assets/fe5611e9-f642-4351-9d3a-0e48c13cac93)

**Comment by diamante0018** [comment]
Oh well...
