### ISSUE TITLE
Screen recorders/overlays not working in fullscreen mode

### ISSUE THREAD

**Issue by Dss0** [IW4x/iw4x-client#13]
When having screen software like nvidia shadowplay or other overlays enabled the game will show a blank screen and stop responding when launched in fullscreen mode. Additionally it's impossible to record the game in fullscreen mode. This is probably related to the anticheat.

**Comment by iw4x-dev-urandom** [comment]
I think I can confirm that this is because of the anticheat blocking access to the game's render buffer as much as blocking the loading of any DLL to handle it. Current workaround is to use a software that allows recording via the screen output itself instead.

**Comment by momo5502** [comment]
Or disable the anticheat

**Comment by Dss0** [comment]
Yea ofc but that's not really a good solution. It still keeps alot of retards from cheating even tho it's easily bypassed.

**Comment by sasseries** [comment]
There are already modified DirectDraw (ddraw.dll) librairies that bypasses the D3D check and allows to load other malicious librairies... Past that point it's up to the rest of the anticheat to do the job.

Point is, if the D3D protections can easily be bypassed and are causing more harm than good, maybe removing the all the DirectX-related checks and let the rest of the AC handle it all could actually be a solution. But hey that's just my two cents on this...
