### ISSUE TITLE
Mod/Map download speed decreasing

### ISSUE THREAD

**Issue by Dss0** [IW4x/iw4x-client#14]
When downloading a mod or map from a server the download speed will gradually decrease to about 150-200KB/s. This issue was not present in 0.5.4 and seems to be clientside because it also exists when downloading from a 0.5.4 server. This issue also exists when downloading from an external webserver.

**Comment by momo5502** [comment]
A client side fix has been implemented to use MS http. Mongoose is just slow. The dedi still uses mongoose to serve the files. If that doesn't help, then servers need to use fast download or mongoose has to be replaced entirely
