### ISSUE TITLE
Uncheat bg_playercollision

### ISSUE THREAD

**Issue by LukkDev** [iw4x/iw4x-client#147]
**What problem will this solve?**
I have an issue with my server where I can turn off bg_playercollision from the server side but not from the client side (at is it now a protected dvar), so when passing through other players there is a lag issue.

**What might be a solution?**
Put back **bg_playercollision** (and maybe bg_playerEjection) to Game::DVAR_CODINFO and not DVAR_CHEAT anymore.

**What other alternatives have you already considered?**
Made a custom build (with the source code) for my server players. (which is not perfect because ill have to make a new one on every new update/release).

**Anything else we should know?**
No.

**Comment by Rackover** [comment]
Related to https://github.com/iw4x/iw4x-client/issues/61
