### ISSUE TITLE
Create a Game Map selection - Description for Firing Range shows <DESCRIPTION NEEDED>

### ISSUE THREAD

**Issue by BOTsofWar-MADDAD** [iw4x/iw4x-client#149]
In the file
iw4x_00.iwd\ui_mp\settings_map.menu
MPUI_DESC_MAP_FIRINGRANGE not working
you just get DESCRIPTION NEEDED

at line
LOCAL_MAP_SELECTION(10, "mp_firingrange",		"MPUI_FIRINGRANGE",		"MPUI_DESC_MAP_FIRINGRANGE",	"preview_mp_firingrange",		dvarint("iw4x_maps_dlc") == 3)

Should show description in game as: Close range to medium range combat in a military practice facility in Cuba

As a workaround I have replaced "MPUI_DESC_MAP_FIRINGRANGE" with "Close range to medium range combat in a military practice facility in Cuba" in my  Client file

**Comment by Rackover** [comment]
https://github.com/iw4x/iw4x-rawfiles/blob/develop/raw/english/iw4x_localized_english.json 
This one? 
This is a probably an issue for iw4x-rawfiles you want to open, this is unrelated to client code :I
