### ISSUE TITLE
-nosteam flag has no effect

### ISSUE THREAD

**Issue by strafe** [IW4x/iw4x-client#18]
Specifying `-nosteam` seems to have no effect. Steam friends are fetched regardless of its presence and can be seen in the main menu of the game.

I've tried all the setups I can think of to eliminate other possibilities. Launching with a shortcut, launching as a non-Steam game, and checking the _"Run this program as an administrator"_ checkbox (both on the executable, the shortcut, and both at the same time).

The only solution is to close Steam entirely, which isn't ideal.

**Comment by momo5502** [comment]
The -nosteam doesn't disable steam. It only disables the transmission of your user data to steam, aka it hides the status of the game you are playing and doesn't broadcast any information to your friends. But it still loads the friendslist. It's basically like a show-as-offline status option.
