### ISSUE TITLE
Linux Wine Crashing

### ISSUE THREAD

**Issue by mikeehun** [IW4x/iw4x-client#20]
I'm trying to run the client with:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.10
Release:	19.10
Codename:	eoan

$ lspci | rg -i nvidia
01:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)

$ modinfo nvidia | rg version
version:        440.31
srcversion:     AB79AD7C98F76A2AC445C90

WINE version: **ge-protonified-nofshack-4.9-x86_64**
Default options, no DVXK, D9VK or Esync
```

The game boots in to the menu, and everything seems to be working, but when I try to connect to any server it crashes with:

`Fatal error (0x80000100) at 0x7B453C5C`

**Comment by RektInator** [comment]
Do you have any crashdump? We can't do anything without a crashdump. Also relevant, what version of wine are you running?

**Comment by mikeehun** [comment]
I have the wine version mentioned in the original post @RektInator I tried `tkg-4.6-x86_64` and `Proton-4.11` as well. 

Can you please suggest how to make a crashdump?
Btw can you run it under linux? If so can you share your setup?

Thanks

**Comment by RektInator** [comment]
You can run IW4x on linux however I haven't done it before, a crashdump is automatically generated after a crash.

**Comment by mikeehun** [comment]
Okay, thanks @RektInator here's the dump: https://mega.nz/#!rY8WBCCB!0ANcp8B5Xn6aaRgpZHHQ88KRD6ex9xETDJ9R05qfUJ0

**Comment by jmarewski** [comment]
How did you even get that far @mikeehun? If I run using proton all i see is a shell popping up. Using wine I see nothing..

**Comment by mikeehun** [comment]
I used **lutris** to setup the runner for it @jmarewski, but I've decided it's not worth my time to investigate further at this point, and I'm back to dual booting win10.

**Comment by jmarewski** [comment]
Ok, using lutris I got a black screen:
Call from 0x7b03214f to unimplemented function secur32.dll.AcquireCredentialsHandleW
Then switching to wine gave a similar error with no window at all.

However switching back to lutris THE GAME RUNS!!!

**Comment by mikeehun** [comment]
Can you connect to server session successfully @jmarewski ?

**Comment by jmarewski** [comment]
Yes everything works fine. I even have less problems then my mate using windows. Played like 4 hours today with only a single crash. @mikeehun

**Comment by h3o66** [comment]
I can also confirm that the game now works on lutris-5.5-2 runner - also played one round already as a test

**Comment by alternaxx** [comment]
@jmarewski Could you please send me a bottle for IW4X? I am trying to get this working on macos Catalina but I am still getting an freeze when I trying to connect to the server. LastLog tells me that the RSAENH.DLL is not loaded from windows/system32. I tried to replace this dll with every possible version of this dll from windows xp/7/8/8.1/10 and unfortunatelly none of these files works :( I don't think that Lutris works on macos but maybe I could take the RSAENH.DLL from it and test it on my wrapper, what do you think? :)
