### ISSUE TITLE
Heartbeat Bandwidth

### ISSUE THREAD

**Issue by geckotdf** [iw4x/iw4x-client#60]
**What are you trying to do?**
Improve standby bandwidth of server.

**What problem are you having?**
The dedicated server send every 3 minutes as far I can check in Grafana probably it's the heartbeat, but sends and receive almost 2 mbps of data for a half of a second, and at the end of the day that's a lot of bandwidth. 
Probably it's because of the Node system or something like that. 

**What version of IW4x are you using?**
Last one

I attach the image of the panel
![Iw4x](https://github.com/iw4x/iw4x-client/assets/30639137/6e8b8032-075e-40b0-b3ae-3d4f7f9614a3)

Thanks!

**Comment by diamante0018** [comment]
it's probably the node system, the heartbeat is a few bytes every 15 minutes so you are referring to something else with the wrong terminology. Not too sure why you would badly crop the screenshot so the vertical axis values are hidden but I'll take your word. 
Umm what's the problem? you are complaining about a small burst of 2bmps every amount of minutes? i think it can't be improved by much because that's the basis for the node system

**Comment by geckotdf** [comment]
Hi,
I don't include the vertical axis because it's out of range sometimes, and it's not detailed. 
That's why I put the mouse over one of the pulses to see the 155kB/s more or less of output and input traffic. 

It's not a complain, I just want to understand the reason, that because in the first post I say: "_Probably it's because of the Node system or something like that_." 
If that the reason and it's not possible to improve it's ok. 
But the reason why ask this it's not because almost 2.5 mbps symmetrical bandwidth it's consume every 3 minutes, it's because that bandwidth at the end of the day it's more or less 2.4 GB of data just to be in stand by when you translate this to a complete month you have 72 GB + or - of wasted bandwidth.

**Comment by diamante0018** [comment]
Sorry if I did not understand your original answer. It's just that often we get complaints 😂 
I don't think the bandwidth usage can be improved, that's my final answer. I hope that that explains it to you.
That's the node system 90% sure, there is no other timely resource in IW4x that would match that apart from the node.
I hope that's it and if my answer is satisfactory please close this issue as complete.
