### ISSUE TITLE
+Connect command line

### ISSUE THREAD

**Issue by geckotdf** [iw4x/iw4x-client#71]
_Do not open an issue here if you need help with modding or have a problem getting the client to run.
Ask in `iw4x-support` or `iw4x-modding` channels on the [Discord](https://discord.gg/tKTQJxcCkk) server if you still have problems.
If this does not apply, please continue by filling in the template below._

**What are you trying to do?**
Use the +connect command in the shortcut of IW4x.exe

**What problem are you having?**
The game open flash for a second the connect splash screen, but get a black screen with the cursor stuck in the middle.

**What have you tried so far?**
I try add -console to get the external console and check any issue and find this, in a fast loop:

![image](https://github.com/iw4x/iw4x-client/assets/30639137/b86f367a-d120-45cf-a96f-9549823947c7)

**What version of IW4x are you using?**
r4416

**Anything else we should know?**
Nothing else.

**Comment by diamante0018** [comment]
This is not how you are supposed to make issue of the hot join feature

You are supposed to open (for example),`Run` with `Windows+R` and type `iw4x://IP:PORT`

**Comment by geckotdf** [comment]
Hi @diamante0018 works as expected now.
I make a shortcut of the .exe and add iw4x://IP:PORT with the correct IP and Port and works perfect.

Thanks for your help!
Have a good year.

**Comment by diamante0018** [comment]
You too, thanks.
