### ISSUE TITLE
Xbox\Playstation buttons aren't showed

### ISSUE THREAD

**Issue by TedMosly** [iw4x/iw4x-client#74]
_Do not open an issue here if you need help with modding or have a problem getting the client to run.
Ask in `iw4x-support` or `iw4x-modding` channels on the [Discord](https://discord.gg/tKTQJxcCkk) server if you still have problems.
If this does not apply, please continue by filling in the template below._

**What are you trying to do?**
play a private match

**What problem are you having?**
Xbox and playstation buttons aren't showed correctly. There are square grey icons instead.

**What have you tried so far?**
re-download the game and reinstall iw4x

**What version of IW4x are you using?**
4423

**Anything else we should know?**
i'm only using bot warfare 2.3.4 mod
![photo_2023-12-21_21-03-00](https://github.com/iw4x/iw4x-client/assets/37401226/018835e0-61b2-42e6-8729-65d535f8f436)

**Comment by TedMosly** [comment]
i tried with a previous build ( r4399 ) and controller buttons icon are showed correctly.

**Comment by Rackover** [comment]
Superseeded by https://github.com/iw4x/iw4x-rawfiles/issues/11
